'use strict';

var function_ = require('../function.js');
var generator = require('./generator.js');

generator('function', function_, {
  valid: [
    ['func { return nil; }'],
    ['func { return 0; }'],
    ['func { 0; return 0; }'],
    ['func {0;0;0;return 0;}'],
    ['func { return "foo";}'],
    ['func { return 1 + 1; }'],
    ['func { return x++; }'],
    ['func { return 1++; }'],
    ['func { return x++ + 1; }'],
    ['func { ++x++; return --3; }'],
    ['func { return --3; }'],
    ['func { return ---x; }'],
    ['func { return ---3; }'],
    ['func { return -- -x; }'],
    ['func { return -a + b; }'],
    ['func { return - - - - -x; }'],
    ['func { return x++ ++; }'],
    ['func { return -- --x; }'],
    ['func { a.b; return a.b++; }'],
    ['func { return a.b++; }'],
    ['func { return a = b; }'],
    ['func { return a ~ b; }'],
    ['func { return a.b = c; }'],
    ['func {foo ~ bar; foo ~ bar; return foo~bar; }'],
    ['func { return foo~bar; }'],
    ['func { return foo~bar++;}'],
    ['func {return foo~++bar++; }'],
    ['func { return a = b = c = d; }'],
    ['func { a.b = b.c = c.d; return a+b+c  ; }'],
    ['func {return return17;}'],
    ['func{false ; return 0;}']
  ],
  invalid: [
    ['func return'],
    ['func => return'],
    ['func{ return nil; }}'],
    ['func{};'],
    [' func{return 0;}'],
    ['func{return 0;} '],
    ['func{{return 0;}'],
    ['func{{return 0;}}'],
    ['func{{{{return 0;}}}}'],
    ['func{{return 3;}}'],
    ['func{1 + 1; {1 + 1;} return 1 + 1;}'],
    ['func{return 0;} '],
    ['func{ return 17; } '],
    ['func{return 17}'],
    ['func{ =>; return 0;}'],
    ['func{=>; return 0;}'],
    ['func{=> ; return 0;}'],
    ['func{==>; return 0;}'],
    ['func{ true}'],
    ['func{ true }'],
    ['func{&; return 0;}'],
    ['func{return 1one;}'],
    ['func{ foo}'],
    ['func{return 7u;}'],
    ['func{3-; return nil;}'],
    ['func{return 1e1.1;}'],
    ['func{return ";}'],
    ['func{return """;}'],
    ['func{(\')}'],
    ['func{(1one)}'],
    ['func{return (,);}'],
    ['func{(foo,); return nil;}'],
    ['func{(,foo); return nil;}'],
    ['func { return 1; return 2; }'],
    ['func{ (); return nil; }'],
    ['func{() }'],
    ['func{|}'],
    ['func{**}'],
    ['func{===}'],
    ['func{!==}']
  ]
});
