'use strict';

var functionBlock = require('../functionBlock.js');
var generator = require('./generator.js');

generator('functionBlock', functionBlock, {
  valid: [
    ['{ return nil; }'],
    ['{ return 0; }'],
    ['{ 0; return 0; }'],
    ['{0;0;0;return 0;}'],
    ['{ return "foo";}'],
    ['{ return 1 + 1; }'],
    ['{ return x++; }'],
    ['{ return 1++; }'],
    ['{ return x++ + 1; }'],
    ['{ ++x++; return --3; }'],
    ['{ return --3; }'],
    ['{ return ---x; }'],
    ['{ return ---3; }'],
    ['{ return -- -x; }'],
    ['{ return -a + b; }'],
    ['{ return - - - - -x; }'],
    ['{ return x++ ++; }'],
    ['{ return -- --x; }'],
    ['{ a.b; return a.b++; }'],
    ['{ return a.b++; }'],
    ['{ return a = b; }'],
    ['{ return a ~ b; }'],
    ['{ return a.b = c; }'],
    ['{foo ~ bar; foo ~ bar; return foo~bar; }'],
    ['{ return foo~bar; }'],
    ['{ return foo~bar++;}'],
    ['{return foo~++bar++; }'],
    ['{ return a = b = c = d; }'],
    ['{ a.b = b.c = c.d; return a+b+c  ; }'],
    ['{return return17;}'],
    ['{false ; return 0;}'],
    ['{ return nil; }'],
    ['{return nil; }'],
    ['{ return nil;}'],
    ['{ return x + y; }'],
    ['{ x = 2 * xParam; return x; }']
  ],
  invalid: [
    ['return'],
    ['{ return nil; }}'],
    ['{};'],
    [' {return 0;}'],
    ['{return 0;} '],
    ['{{return 0;}'],
    ['{{return 0;}}'],
    ['{{{{return 0;}}}}'],
    ['{{return 3;}}'],
    ['{1 + 1; {1 + 1;} return 1 + 1;}'],
    ['{return 0;} '],
    ['{ return 17; } '],
    ['{return 17}'],
    ['{ =>; return 0;}'],
    ['{=>; return 0;}'],
    ['{=> ; return 0;}'],
    ['{==>; return 0;}'],
    ['{ true}'],
    ['{ true }'],
    ['{&; return 0;}'],
    ['{return 1one;}'],
    ['{ foo}'],
    ['{return 7u;}'],
    ['{3-; return nil;}'],
    ['{return 1e1.1;}'],
    ['{return ";}'],
    ['{return """;}'],
    ['{(\')}'],
    ['{(1one)}'],
    ['{return (,);}'],
    ['{(foo,); return nil;}'],
    ['{(,foo); return nil;}'],
    ['{ return 1; return 2; }'],
    ['{ (); return nil; }'],
    ['{() }'],
    ['{|}'],
    ['{**}'],
    ['{===}'],
    ['{!==}'],
    ['{ return nil; '],
    ['({ return nil; }'],
    ['){return nil; }'],
    ['return nil;}'],
    ['(x y) { return x + y; }'],
    ['(xParam) { x = 2 * xParam return x; }']
  ]
});
